language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
jdk:
- oraclejdk8
script:
- ./gradlew clean install build
after_failure:
- cat build/test-results/test/binary/results.bin
