= srcdeps-gradle-dep-maven-git-revision-quickstart

A Gradle project containing a dependency on a source revision of a Maven project

== System requirements

* Gradle 3.5+
* Maven 3.3.1+
* Java 7+ or newer

== Recommended study order

* link:build.gradle :
** `org.srcdeps.gradle.plugin`
** The version of `org.srcdeps.test.gradle:srcdeps-test-artifact-gradle-impl`
* link:srcdeps.yaml[`srcdeps.yaml`] and its documentation under
  https://github.com/srcdeps/srcdeps-core/blob/master/doc/srcdeps.yaml .
* Issue `gradle clean build` on command line in the directory where this README file resides.
* Check in the output of the above `mvn` command if the
  link:jar/src/test/java/org/srcdeps/quickstarts/mvn/git/revision/gradle/GreetingAppTest.java#L27[GreetingAppTest]
  passed
* Check if the version `1.0-SRC-revision-e63539236a94e8f6c2d720f8bda0323d1ce4db0f` of
  `org.srcdeps.test.gradle:srcdeps-test-artifact-gradle-impl` was installed in your local Maven
  repository.
* Check the directory where the `srcdeps-test-artifact` was built:
  `${maven.repo.local}/../srcdeps/org/srcdeps/test/gradle` - i.e. typically
  `~/.m2/srcdeps/org/srcdeps/test/gradle`

== Feedback

via link:https://github.com/srcdeps/srcdeps-gradle-plugin/issues[srcdeps-gradle-plugin Github Issues]